on:
  push:
    branch:
      -main

jobs:
  build:
    name: build app
    runs-on: ubuntu-latest
    steps:
      - name: menampilkan text
        run: echo "this step build"
  test:
    name: test app
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: menampilkan text
        run: echo "this step test"
  deployment:
    name: deploy app
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: menampilkan text
        run: echo "this step deployment"
