on:
  push:
    branch:
      - main
jobs:
  build:
    name: build app
    runs-on: ubuntu-latest
    steps:
      - name: menampilkan text
        run: echo "this step build"
  test:
    name: test app
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: menampilkan text
        run: echo "this step test"
  deployment:
    name: deploy app
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: menampilkan text
        run: echo "this step deployment"
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}  
          script: |
            rm -rf /var/www/html/*
            rm -rf /var/www/html/.git
            rm -rf /var/www/html/.github
            git clone https://github.com/andika1720/HeroBiz /var/www/html/
